"""update_database_schema

Revision ID: f2dc245d0e7b
Revises: 0a5596d21aa5
Create Date: 2025-07-27 13:21:37.321588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2dc245d0e7b'
down_revision: Union[str, Sequence[str], None] = '0a5596d21aa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log_records', sa.Column('risk_factors', sa.Text(), nullable=True))
    op.add_column('log_records', sa.Column('improvement_suggestions', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('log_records', 'improvement_suggestions')
    op.drop_column('log_records', 'risk_factors')
    # ### end Alembic commands ###
